document:
    type: rest
    resource: ApiBundle\Controller\DocumentController

vehicle:
    type: rest
    resource: ApiBundle\Controller\VehicleController

tire:
    type: rest
    resource: ApiBundle\Controller\TireController

store:
    type: rest
    resource: ApiBundle\Controller\StoreController

consumer:
    type: rest
    resource: ApiBundle\Controller\ConsumerController