document:
    type: rest
    resource: ApiBundle\Controller\DocumentController

document_position:
    type: rest
    resource: ApiBundle\Controller\DocumentPositionController

vehicle:
    type: rest
    resource: ApiBundle\Controller\VehicleController

tire:
    type: rest
    resource: ApiBundle\Controller\TireController

store:
    type: rest
    resource: ApiBundle\Controller\StoreController

service:
    type: rest
    resource: ApiBundle\Controller\ServiceController

consumer:
    type: rest
    resource: ApiBundle\Controller\ConsumerController

employee:
    type: rest
    resource: ApiBundle\Controller\EmployeeController

user:
    type: rest
    resource: ApiBundle\Controller\UserController

car_rent:
    type: rest
    resource: ApiBundle\Controller\CarRentController

car_rent_history:
    type: rest
    resource: ApiBundle\Controller\CarRentHistoryController