# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        ApiBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: ApiBundle:User
                property: username

        # in_memory:
        #     memory:
        #         users:
        #             user:
        #                 password: password
        #                 roles: 'ROLE_USER'
        #             admin:
        #                 password: password2
        #                 roles: 'ROLE_ADMIN'

    firewalls:

        dev:
            pattern: ^/(_profiler|_wdt|css|images|js)/
            security: false
            stateless: true
            anonymous: true

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        registration:
            pattern:  ^/registration
            stateless: true
            anonymous: true

        profiler:
            pattern:  ^/_profiler
            stateless: true
            anonymous: true

        check_username:
            pattern:  ^/username_check
            stateless: true
            anonymous: true

        email:
            pattern:  ^/email_check
            stateless: true
            anonymous: true

        api:
            pattern:   ^/
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            pattern: .*
            anonymous: true
            switch_user:  true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/username_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/email_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_wdt|_profiler), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
