# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    crv.doctrine_entity_repository.document:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - ApiBundle\Entity\Document

    crv.doctrine_entity_repository.document_position:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - ApiBundle\Entity\DocumentPosition

    crv.doctrine_entity_repository.vehicle:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - ApiBundle\Entity\Vehicle

    crv.doctrine_entity_repository.tire:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - ApiBundle\Entity\Tire

    crv.doctrine_entity_repository.store:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - ApiBundle\Entity\Store

    crv.doctrine_entity_repository.service:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - ApiBundle\Entity\Service

    crv.doctrine_entity_repository.consumer:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - ApiBundle\Entity\Consumer

    crv.doctrine_entity_repository.employee:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - ApiBundle\Entity\Employee

    crv.doctrine_entity_repository.user:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - ApiBundle\Entity\User

    crv.doctrine_entity_repository.car_rent:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - ApiBundle\Entity\CarRent

    crv.doctrine_entity_repository.car_rent_history:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - ApiBundle\Entity\CarRentHistory

    crv.doctrine_entity_repository.service_order:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - ApiBundle\Entity\ServiceOrder

    crv.doctrine_entity_repository.service_order_position:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - ApiBundle\Entity\ServiceOrderPosition

    utils.document_number.generate:
        class: ApiBundle\Utils\DocumentNumberGenerator
        arguments: ['@service_container']