<?php

namespace ApiBundle\Repository;

/**
 * CarRentHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRentHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
