<?php

namespace ApiBundle\Repository;

/**
 * CarRentHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRentHistoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function createFindOneByIdQuery(int $id, int $userId)
    {
        $query = $this->_em->createQuery(
            "
            SELECT d
            FROM ApiBundle:CarRentHistory d
            WHERE d.id = :id
            AND d.userId = :userId
            "
        );

        $query->setParameter('id', $id);
        $query->setParameter('userId', $userId);

        return $query;
    }

    public function createFindByRentIdQuery(int $carId, int $userId)
    {
        $query = $this->_em->createQuery(
            "
            SELECT d
            FROM ApiBundle:CarRentHistory d
            WHERE d.userId = :userId
            AND d.carId = :carId
            "
        );

        $query->setParameter('userId', $userId);
        $query->setParameter('carId', $carId);

        return $query;
    }

    public function createFindLastQuery(int $carId, int $userId)
    {
        $query = $this->_em->createQuery(
            "
            SELECT d
            FROM ApiBundle:CarRentHistory d
            WHERE d.userId = :userId
            AND d.carId = :carId
            ORDER BY d.id DESC
            "
        );

        $query->setParameter('userId', $userId);
        $query->setParameter('carId', $carId);
        $query->setMaxResults(1);

        return $query;
    }
}
