<?php

namespace ApiBundle\Repository;

/**
 * ConsumerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsumerRepository extends \Doctrine\ORM\EntityRepository
{
    public function createFindOneByIdQuery(int $id, int $userId)
    {
        $query = $this->_em->createQuery(
            "
            SELECT d
            FROM ApiBundle:Consumer d
            WHERE d.id = :id
            AND d.userId = :userId
            "
        );

        $query->setParameter('id', $id);
        $query->setParameter('userId', $userId);

        return $query;
    }

    public function createFindAllQuery(int $userId)
    {
        $query = $this->_em->createQuery(
            "
            SELECT d
            FROM ApiBundle:Consumer d
            WHERE d.userId = :userId
            "
        );

        $query->setParameter('userId', $userId);

        return $query;
    }

    public function searchQuery(int $userId, string $searchStr, string $orderBy, string $sort)
    {
        if($orderBy!='')
        {
            if($orderBy == 'name' || 
                $orderBy == 'namesurname' || 
                $orderBy == 'company' || 
                $orderBy == 'phone' || 
                $orderBy == 'email')
            {
                $orderBy = 'ORDER BY d.'.$orderBy;
            }else{
                $orderBy = '';
            }
        }
        if($sort!='')
        {
            if(($sort == 'ASC' || $sort == 'DESC') && $orderBy != '')
            {
                $sort = $sort;
            }else{
                $sort = '';
            }
        }

        $sorting = $orderBy.' '.$sort;

        $query = $this->_em->createQuery(
            "
            SELECT d
            FROM ApiBundle:Consumer d
            WHERE d.userId = :userId
            AND (d.company LIKE :searchStr
            OR d.name LIKE :searchStr
            OR d.nip LIKE :searchStr
            OR d.phone LIKE :searchStr
            OR d.email LIKE :searchStr
            OR d.www LIKE :searchStr
            OR d.street LIKE :searchStr
            OR d.place LIKE :searchStr
            OR d.postalCode LIKE :searchStr
            OR d.post LIKE :searchStr
            OR d.notes LIKE :searchStr)
            ".$sorting
        );

        $query->setParameter('userId', $userId);
        $query->setParameter('searchStr', '%'.$searchStr.'%');

        return $query;
    }

}
