<?php

namespace ApiBundle\Repository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{

    public function createFindOneByIdQuery(int $id, int $userId)
    {
        $query = $this->_em->createQuery(
            "
            SELECT d
            FROM ApiBundle:Document d
            WHERE d.id = :id
            AND d.userId = :userId
            "
        );

        $query->setParameter('id', $id);
        $query->setParameter('userId', $userId);

        return $query;
    }

    public function createFindByConsumerIdQuery(int $id, int $userId)
    {
        $query = $this->_em->createQuery(
            "
            SELECT d
            FROM ApiBundle:Document d
            WHERE d.consumerId = :id
            AND d.userId = :userId
            "
        );

        $query->setParameter('id', $id);
        $query->setParameter('userId', $userId);

        return $query;
    }

    public function createFindByTypeQuery($type, int $userId)
    {
        $query = $this->_em->createQuery(
            "
            SELECT d
            FROM ApiBundle:Document d
            WHERE d.type = :type
            AND d.userId = :userId
            "
        );
        if($type=='bills')
            $type="Rachunek";
        else if($type=='invoices')
            $type="FV";
        else
            $type="";

        $query->setParameter('type', $type);
        $query->setParameter('userId', $userId);

        return $query;
    }

    public function createFindAllQuery(int $userId)
    {
        $query = $this->_em->createQuery(
            "
            SELECT d
            FROM ApiBundle:Document d
            WHERE d.userId = :userId
            "
        );

        $query->setParameter('userId', $userId);

        return $query;
    }
}