<?php

namespace ApiBundle\Repository;

/**
 * DocumentPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentPositionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByDocumentId($id)
	{
		return $this->getEntityManager()
		->createQuery(
		      "SELECT
		      		d.id,
		      		d.name,
		      		d.netto,
		      		d.brutto,
		      		d.vat,
		      		d.vatSum,
		      		d.quantity
		      	FROM
		      		ApiBundle:DocumentPosition d
		      	WHERE
		      		d.documentId = ".$id
		)
		->getResult();
	}
}
