<?php

namespace ApiBundle\Repository;

/**
 * DocumentPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentPositionRepository extends \Doctrine\ORM\EntityRepository
{
    public function createFindOneByIdQuery(int $id, int $userId)
    {
        $query = $this->_em->createQuery(
            "
            SELECT d.id,
                d.documentId,
                d.service,
                d.itemId,
                d.name,
                d.netto,
                d.vat,
                d.vatSum,
                d.brutto,
                d.quantity
            FROM ApiBundle:DocumentPosition d
            WHERE d.id = :id
            AND d.userId = :userId
            "
        );

        $query->setParameter('id', $id);
        $query->setParameter('userId', $userId);

        return $query;
    }

    public function createUpdateQuery(int $id, int $userId)
    {
        $query = $this->_em->createQuery(
            "
            SELECT d
            FROM ApiBundle:DocumentPosition d
            WHERE d.id = :id
            AND d.userId = :userId
            "
        );

        $query->setParameter('id', $id);
        $query->setParameter('userId', $userId);

        return $query;
    }

    public function createFindByDocumentIdQuery(int $documentId, int $userId)
    {
        $query = $this->_em->createQuery(
            "
            SELECT d.id,
                d.documentId,
                d.service,
                d.itemId,
                d.name,
                d.netto,
                d.vat,
                d.vatSum,
                d.brutto,
                d.quantity
            FROM ApiBundle:DocumentPosition d
            WHERE d.documentId = :documentId
            AND d.userId = :userId
            "
        );

        $query->setParameter('documentId', $documentId);
        $query->setParameter('userId', $userId);

        return $query;
    }

}
