<?php

namespace ApiBundle\Repository;

/**
 * DocumentPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
