<?php

namespace ApiBundle\Repository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList()
    {
        return $this->getEntityManager()
            ->createQuery("
                SELECT
                    e
                FROM
                    ApiBundle:Employee e
            ")
            ->getArrayResult();
    }

    public function getById($id)
    {
        return $this->getEntityManager()
            ->createQuery("
                SELECT
                    e
                FROM
                    ApiBundle:Employee e
            ")
            ->getArrayResult();
    }
}
