<?php

namespace ApiBundle\Repository;

/**
 * ServiceOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
