<?php

namespace ApiBundle\Repository;

/**
 * ServiceOrderPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceOrderPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
