<?php

namespace ApiBundle\Repository;

/**
 * TireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TireRepository extends \Doctrine\ORM\EntityRepository
{
}
