<?php

namespace ApiBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getId($username)
    {
        $user = $this->getEntityManager()
            ->createQuery("SELECT
                    u.id
                FROM
                    ApiBundle:User u
                WHERE
                    u.username = '$username'"
            )
            ->getArrayResult();
        return $user['0']['id'];
    }
}