version: '3.1'
services:
  db:
    image: mysql:5.7
    container_name: mysql-warsztat
    volumes:
       - ./var/mysql:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: warsztat
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: very-secret

  php:
    build: ./docker/php
    container_name: php-warsztat
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./:/var/www

  web:
    image: nginx
    container_name: nginx-warsztat
    depends_on:
      - db
      - php
    links:
      - php
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    environment:
      NGINX_HOST: warsztat.com
      NGINX_PORT: 80
